const ROLES = {
  ADMIN: "ADMIN",
  CAJERO: "CAJERO",
  VENDEDOR: "VENDEDOR",
  REPARTIDOR: "REPARTIDOR",
};

const SALE_STATUS = {
  PENDIENTE: "PENDIENTE",
  PREPARADO: "PREPARADO",
  CARGADO: "CARGADO",
  ANULADO: "ANULADO",
};

const DELIVERY_STATUS = {
  BORRADOR: "BORRADOR",
  CARGA_CERRADA: "CARGA_CERRADA",
};

module.exports = { ROLES, SALE_STATUS, DELIVERY_STATUS };

